spring:
  web:
    resources:
      static-locations: classpath:/static/
  application:
    name: freenanum
  datasource:
    url: jdbc:mysql://211.188.50.38/freenanum
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1000000
      pool-name: HikariCP
  data:
    redis:
      host: 211.188.50.38
      port: 6379
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
    show-sql: true
  sql:
    init:
      mode: always
  jackson:
    time-zone: UTC
jwt:
  secret: V/CjhO4NzYQDTxd91K+voBmi9BE7gRj2i65sNvKHOd8=

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /**

