spring:
  application:
    name: freenanum

  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/freenanum
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1000000
      pool-name: HikariCP

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: 1234

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    encoding: UTF-8

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
    show-sql: true

  # DevTools 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  # Jackson 설정
  jackson:
    time-zone: UTC

  # JWT 설정
jwt:
  secret: V/CjhO4NzYQDTxd91K+voBmi9BE7gRj2i65sNvKHOd8=
  expiration: 3600000  # 만료 시간 (1시간)

  # Swagger 설정
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    default-models-expand-depth: 2
    default-model-expand-depth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /**